---
- name: Add the ossec.wazuh Repository
  lineinfile: "dest=/etc/apt/sources.list state=present regexp='^' line='deb http://ossec.wazuh.com/repos/apt/ubuntu trusty main'"
  when: ansible_distribution_version == "trusty" and ansible_distribution == "ubuntu"

- name: Install ossec and any dependencies
  apt: pkg={{item}} state=installed update_cache=yes force=yes
  with_items:
    - ossec-hids-agent

- fail: msg="The system may not be provisioned because yum"
  when: ansible_distribution == "centos"

- name: Create tmp and var directories for ossec
  file: path={{ item }} state=directory
  with_items:
    - "{{ ossec_tmp }}"
    - "/var/ossec/etc"
  
- name: Copy the ossec_input file
  template: src=ossec_client_input.j2 dest="{{ ossec_tmp }}/ossec_client_input.txt"

- name: Copy the ossec.conf file
  template: src=ossec.conf.j2 dest="/var/ossec/etc/ossec.conf"
 
- name: Get the client key from server
  copy: src=/tmp/client.keys dest=/var/ossec/etc/client2.keys  
 
- name: Extract only the key for current client
  shell: grep "{{ ansible_ssh_host }}" /var/ossec/etc/client2.keys > /var/ossec/etc/client.keys
 
- name: Delete other client keys   
  file: name=/var/ossec/etc/client2.keys state=absent
 
- name: Start Ossec server
  service: name=ossec state=started
