---
galaxy_info:
  author: Werner Dijkerman
  description: INstalling and maintaining the ossec-agent.
  company: myCompany.Dotcom
  license: license (GPLv3)
  min_ansible_version: 1.4
  platforms:
  - name: EL
    versions:
    - 5
    - 6
    - 7
  - name: Fedora
    versions:
    - all
  #- name: opensuse
  #  versions:
  #  - all
  #  - 12.1
  #  - 12.2
  #  - 12.3
  #  - 13.1
  #  - 13.2
  #- name: Ubuntu
  #  versions:
  #  - all
  #  - lucid
  #  - maverick
  #  - natty
  #  - oneiric
  #  - precise
  #  - quantal
  #  - raring
  #  - saucy
  #  - trusty
  - name: Debian
    versions:
    - all
  categories:
  - monitoring
#dependencies: []
  # List your role dependencies here, one per line. Only
  # dependencies available via galaxy should be listed here.
  # Be sure to remove the '[]' above if you add dependencies
  # to this list.
  
