- name: Ansible Tower Server (old - api)
  hosts: oldtower
  roles:
    - { role: sumologic, sumo_collector_config_file: 'tower-collector.json', sumo_machine_id: 'ansible_tower_old', tags: ['sumologic'] }