---
# file: devops-ansible/harden.yaml
# Examples:
#   ansible-playbook -vvvv -i hosts/harden.ini harden-server.yaml --extra-vars "ssh-user=ec2-user ansible-distribution=CentOS"
#   ansible-playbook -vvvv -i hosts/harden.ini harden-server.yaml --extra-vars "ssh-user=ubuntu ansible-distribution=ubuntu"
#
#   ansible-playbook -vvvv -i hosts/harden.ini harden-server.yaml -e "@includes/users.yaml" -e "@includes/groups.yaml" -e "@includes/keys.yaml"




- hosts: all
  name: Server Hardening
  user: { ssh-user }
  gather_facts: true
  tasks:
    - name: Install Ruby Gem for Ansible-Tower
      command: sudo apt-get install ruby && sudo gem install iron_worker_ng -v 1.6.4

  roles:
    - { role: auto-upgrades, tags: "auto-upgrades", sudo: yes }

  vars:
   # ansible_distribution: CentOS
