---
# file: devops-ansible/jumpserver.yaml
# Examples:
#   ansible-playbook -vvvv -i hosts/jumpservers.ini jumpserver-deploy.yaml -e "@includes/users.yaml" -e "@includes/groups.yaml" -e "@includes/keys.yaml"
#   (SUMO) ansible-playbook -vvvv -i hosts/jumpservers.ini jumpserver-deploy.yaml -e "@includes/users.yaml" -e "@includes/groups.yaml" -e "@includes/keys.yaml dosumo=yay" --vault-password-file="~/.vault_pass.txt" 

- hosts: jumpservers

  roles:
    - { role: common, tags: "common" }
    - { role: jumpserver, tags: "jumpserver" }
#    - { role: sshd, tags: "sshd" }
#    - { role: ansible-users, tags: "ansible-users" }
#    - include_vars: includes/users.yaml
#    - include_vars: includes/keys.yaml
#    - { role: user_management, tags: "user_management" }
#    - { role: sumologic, tags: "sumologic" }
#    - { role: papertrail, tags: "papertrail" }
  sudo: yes
#     - include_vars: includes/users.yaml
#     - include_vars: includes/keys.yaml
  vars:

    users_admin_sudo_password: false
#  roles:
#  - role: ansible-users
#    users:
#    - name: carl
#      uid: 1010
#      comment: 'Carl Crisp'
#      is_admin: yes
#      groups:
#      - beancounters
#    - name: ec_user
#      state: absent
#    users_groups:
#    - name: beancounters
#    users_ssh_keys:
#    - name: carl
#      keys:
#      - ssh-rsa AAAA....... carl@accounts.example.com

  #  - include: includes/users.yaml
