---
# file: devops-ansible/jumpserver360.yaml

# Description:
#   Launch jumpserver instances

# Preconditions:
#   export AWS_ACCESS_KEY_ID=
#   export AWS_SECRET_ACCESS_KEY=

# Examples:
#
#  TESTING
#    ansible-playbook jumpserver360.yaml -i hosts/jumpservers.ini --extra-vars "counter_tag=devops-bastion-`date '+%Y%m%d'` server_name=devops:shared:bastion-tmp1 role=jump_server instance_count=1"
#    ansible-playbook jumpserver360.yaml -i hosts/jumpservers.ini --extra-vars "counter_tag=devops-bastion-`date '+%Y%m%d'`-tmp1 server_name=devops:shared:bastion-tmp1 role=jump_server instance_count=1" -vvvv
#
# PRODUCTION
# bastion-a
#    ansible-playbook jumpserver360.yaml -i hosts/jumpservers.ini --extra-vars "counter_tag=devops-bastion-a server_name=devops:shared:bastion-a role=jump_server instance_count=1 vpc_subnet_id=subnet-d47effff"
#
# bastion-b
#    ansible-playbook jumpserver360.yaml -i hosts/jumpservers.ini --extra-vars "counter_tag=devops-bastion-b server_name=devops:shared:bastion-b role=jump_server instance_count=1 vpc_subnet_id=subnet-72ee9505"
#

- name: Launch/configure app server instance
  hosts: 127.0.0.1
  connection: local
  gather_facts: false

  vars:
    instance_type: "t2.micro"   
    region: us-east-1
    server_name: devops:undefined:bastion
    role: null
    #role: ansible
    #image: ami-d0ba0cb8 # base ubuntu 14.04 : us-east-1, 64-bit, instance root store
    image: ami-d05e75b8 # Devops testing for jumpserver
    
    #sage_aws_group: devops-default-vpc
    #aws_group: allow-wfm-ssh
    aws_security_group: bastion
    #vpc_subnet_id: subnet-ced06eb9  # Testing Subnet
    #vpc_subnet_id: subnet-d47effff  # bastion a
    #vpc_subnet_id: subnet-72ee9505   # bastion b

  tasks:
    - name: Launch server
      local_action:
        module: ec2
        vpc_subnet_id: "{{ vpc_subnet_id }}"
        assign_public_ip: yes
        key_name: wfm-devops-root
        group: "{{ aws_security_group }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        region: "{{ region }}"
        wait: yes
        wait_timeout: 500
        exact_count: "{{ instance_count | default(1) }}"
        count_tag:
          #counter_tag: "{{ counter_tag }}"
          Name: "{{ server_name }}"
      register: ec2_instances

#    - include: includes/build-ec2-inventory.yaml

    - name: Tag instances
      local_action: ec2_tag
                    resource={{ item.id }}
                    region={{ region }}
                    state=present
      with_items: ec2_instances.tagged_instances
      args:
        tags:
          Name: "{{ server_name }}"
          #counter_tag: "{{ counter_tag }}"
          #role: "{{ role }}"
          #owner: devops
          "wfm:team": devops
          "wfm:environment": shared

    - name: wait for instances to listen on port:22
      wait_for: state=started
                host={{ item.public_dns_name }}
                port=22
      with_items: ec2_instances.tagged_instances

    - name: Report instances to user
      debug: msg="Instance {{ item.id }} with public IP {{ item.public_ip }}"
      with_items: ec2_instances.instances

#    - name: Notify Hipchat
#      hipchat:
#        token={{ default_hipchat_token }}
#        room={{ default_hipchat_room }}
#        from={{ default_hipchat_from }}
#        msg="Ansible Created {{ counter_tag }} {{ instance_type }} Instance {{ item.id }} with public IP {{ item.public_ip }} serving subnet {{ vpc_subnet_id }}"
#        validate_certs=no
#      ignore_errors: yes   # DO NOT FAIL IF HIPCHAT IS DOWN
#      with_items: ec2_instances.instances

    - name: Add all instance public IPs to host group
      add_host: hostname={{ item.public_ip }}
                groupname=ec2hosts.base
                groups=ec2hosts.base
                ansible_ssh_private_key_file=~/.ssh/wfm-devops-root.pem
                ansible_ssh_user=ubuntu
      with_items: ec2_instances.tagged_instances

- hosts: ec2hosts.base
  name: configuration play
  #user: ec2-user
  user: ubuntu
  gather_facts: true
  tasks:
    - include_vars: includes/ec2hosts.accounts.yaml
  roles:
    - { role: common, tags: "common", sudo: yes }
    - { role: jumpserver, tags: "jumpserver", sudo: yes }
    - { role: ansible-users, tags: "ansible-users", sudo: yes }
