--
# file: devops-ansible/jumpserver.yaml

# Examples:
#   ansible-playbook jumpservers.yaml -i hosts/development.ini
#   (SUMO) ansible-playbook jumpservers.yaml -i hosts/development.ini --extra-vars="dosumo=yay" --vault-password-file=~/.vault_pass.txt


- hosts: jumpservers
  roles:
    - common
