---
# file: devops-ansible/jumpserver-deploy.yaml
# Examples:
#   ansible-playbook -vvvv -i hosts/jumpservers.ini jumpserver-deploy.yaml -e "@includes/users.yaml" -e "@includes/groups.yaml" -e "@includes/keys.yaml"
#   (SUMO) ansible-playbook -vvvv -i hosts/jumpservers.ini jumpserver-deploy.yaml -e "@includes/users.yaml" -e "@includes/groups.yaml" -e "@includes/keys.yaml dosumo=yay" --vault-password-file="~/.vault_pass.txt" 

# bastion-a
#    ansible-playbook jumpserver-deploy.yaml -i hosts/jumpservers.ini --extra-vars "counter_tag=devops-bastion-a server_name=devops:shared:bastion-a role=jump_server instance_count=1 vpc_subnet_id=subnet-d47effff"
#
# bastion-b
#    ansible-playbook jumpserver-deploy.yaml -i hosts/jumpservers.ini --extra-vars "counter_tag=devops-bastion-b server_name=devops:shared:bastion-b role=jump_server instance_count=1 vpc_subnet_id=subnet-72ee9505"

- hosts: jumpservers
  user: service-tower21
  vars:
  - include: includes/ec2hosts.accounts.yaml
  - included_vars: includes/ec2hosts.accounts.yaml
#  - included_vars: group_vars/ec2hosts.accounts
#  - included_vars: group_vars/jumpservers
    users_admin_sudo_password: false
  roles:
    - { role: common, tags: "common" }
    - { role: jumpserver, tags: "jumpserver" }
    - { role: ansible-users, tags: "ansible-users" }
    - include: includes/ec2hosts.accounts.yaml
#    - include: group_vars/ec2hosts.accounts
#    - { role: sumologic, tags: "sumologic" }
#    - { role: papertrail, tags: "papertrail" }
  sudo: yes
