---
# file: devops-ansible/ec2-launch-instance.yaml

# Description:
#   Attempt to launch ec2 instances 
#   This file was borrowed from wfm-api team. Thanks.

# Preconditions:
#   export AWS_ACCESS_KEY_ID=
#   export AWS_SECRET_ACCESS_KEY=

# Examples:
#  *** REPLACE DDMMYYYYa IN THESE EXAMPLES ***

#    ansible-playbook jumpserver360.yaml -i hosts/jumpservers.ini --extra-vars "counter_tag=devops-jumpserver-`date '+%Y%m%d'` server_name=devops-bastion-a role=jump_server instance_count=1"
#    ansible-playbook jumpserver-launch-instance.yaml -i hosts/local-binpy.ini --extra-vars "counter_tag=devops-jumpserver-`date '+%Y%m%d'` server_name=devops-bastion-a role=app_server instance_count=1 instance_type=t2.micro"
#    ansible-playbook jumpserver-launch-instance.yaml -i hosts/local-binpy.ini --extra-vars "counter_tag=devops-jumpserver-`date '+%Y%m%d'` server_name=devops-bastion-a role=app_server instance_count=1 instance_type=t2.micro"

# TODOs:
#   Fix "report instances to user" to check for id before printing to avoid errors
#   Need to automate adding elastic ip to newly launched server
#   Make vars: image: a global variable since it is a standard (BEWARE: make sure it works on Tower)

# WARNINGS:
#   counter_tag is used to limit number of servers launched.
#   Make counter_tag unique per deployment if you're rotating servers in and out of a load balancer

- name: Launch/configure app server instance
  hosts: 127.0.0.1
  connection: local
#  gather_facts: false

  vars:
    instance_type: "t2.micro"   
    region: us-east-1
    server_name: devops:shared:bastion
    role: null
    #role: ansible
    #image: ami-d0ba0cb8 # base ubuntu 14.04 : us-east-1, 64-bit, instance root store
    image: ami-d05e75b8 # Devops testing for jumpserver
    
    #sage_aws_group: devops-default-vpc
    aws_group: allow-wfm-ssh
    #vpc_subnet_id: subnet-ced06eb9  # Testing Subnet
    vpc_subnet_id: subnet-d47effff  # bastion a
    #vpc_subnet_id: subnet-72ee9505   # bastion b

  tasks:
    - name: Launch server
      local_action:
        module: ec2
        vpc_subnet_id: "{{ vpc_subnet_id }}"
        assign_public_ip: yes
        key_name: wfm-devops-root
        group: "{{ aws_group }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        region: "{{ region }}"
        wait: yes
        wait_timeout: 500
        exact_count: "{{ instance_count | default(1) }}"
        count_tag:
          counter_tag: "{{ counter_tag }}"
      register: ec2_instances

#    - include: includes/build-ec2-inventory.yaml

    - name: Tag instances
      local_action: ec2_tag
                    resource={{ item.id }}
                    region={{ region }}
                    state=present
      with_items: ec2_instances.tagged_instances
      args:
        tags:
          Name: "{{ server_name }}"
          counter_tag: "{{ counter_tag }}"
          #role: "{{ role }}"
          #owner: devops
          "wfm:team": devops
          "wfm:environment": shared

    - name: wait for instances to listen on port:22
      wait_for: state=started
                host={{ item.public_dns_name }}
                port=22
      with_items: ec2_instances.tagged_instances

    - name: Report instances to user
      debug: msg="Instance {{ item.id }} with public IP {{ item.public_ip }}"
      with_items: ec2_instances.instances

#    - name: Notify Hipchat
#      hipchat:
#        token={{ default_hipchat_token }}
#        room={{ default_hipchat_room }}
#        from={{ default_hipchat_from }}
#        msg="Ansible Created {{ counter_tag }} {{ instance_type }} Instance {{ item.id }} with public IP {{ item.public_ip }} serving subnet {{ vpc_subnet_id }}"
#        validate_certs=no
#      ignore_errors: yes   # DO NOT FAIL IF HIPCHAT IS DOWN
#      with_items: ec2_instances.instances

    - name: Add all instance public IPs to host group
      add_host: hostname={{ item.public_ip }}
                groupname=ec2hosts
                groups=ec2hosts
                ansible_ssh_private_key_file=~/.ssh/wfm-devops-root.pem
                ansible_ssh_user=ubuntu
      with_items: ec2_instances.tagged_instances

- hosts: ec2hosts
  name: configuration play
  user: ec2-user
  #user: ubuntu
  gather_facts: true

  tasks:
     - name: Check NTP service
       service: name=ntpd state=started

  roles:
    - { role: common, tags: "common" }
    - { role: jumpserver, tags: "jumpserver" }
    - { role: ansible-users, tags: "ansible-users" }
#    - include: includes/users.yaml
#    - include: includes/groups.yaml
#    - include: includes/keys.yaml

# TODO: need to automate adding elastic ip to newly launched server
