---
# file: devops-ansible/natserver.yaml
# Examples:
#   ansible-playbook -vvvv -i hosts/natservers.ini natserver-deploy.yaml --extra-vars "ansible_distribution=CentOS"
#   ansible-playbook -vvvv -i hosts/natservers.ini natserver-deploy.yaml --extra-vars "ansible_distribution=Ubuntu"
#   
# Common Problems:
#    ansible_distribution variable does not get set from hosts/natserver.ini file


- hosts: natservers
  name: configuration play
#  user: ec2-user
  gather_facts: true
 # tasks:

  roles:
    - { role: auto-upgrades, tags: "auto-upgrades", sudo: yes }
    - name: service-tower
      uid: 1010
      comment: service-tower
      password: ''
      #is_admin: no
      groups:
        - sudo

  vars:
    ansible_distribution: CentOS
