---
- hosts: vagrant
  remote_user: vagrant
  sudo: yes
  roles:
    - { role: common, tags: "common" }
    - { role: auto-upgrades, tags: "auto-upgrades" }
    #- { role: nginx, tags: "nginx" }
    - role: ansible-users
      users:
      - name: carl
        uid: 1010
        comment: 'Carl Crisp'
        is_admin: yes
        groups:
        - beancounters
      - name: ec_user
        state: absent
      users_groups:
      - name: beancounters
      users_ssh_keys:
      - name: carl
        keys:
        - ssh-rsa AAAA....... carl@accounts.example.com
      users:
      - name: jtischler
        uid: 1112
        comment: 'jtischler'
        password: '$6$NjsPot/E$bVwycS403QEkC/hAQ1uivCxaxtTWyHSttcRrYylDhtyGav1IrMTATUbz/5TNfp2FiOwCWLhUhTsmzcIsTkTEB/'
        is_admin: yes
        groups:
          - debian-transmission
      users_groups:
      - name: jtischler
        gid: 1112
      - name: sudo
        gid: 27
      users_ssh_keys:
      - name: jtischler
        keys:
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDWBFyNu0yoh9+q4f5olurpQSJWX1CwM54rvXZzytLAn92D1w2yvtzw248IpoauKQxS/YdupVwehI7iViszomJcAQnl9QkNc9Fu0FYF+nGHn1xREIh1DNIX4zKfVLxS6Vpjz5Wa00vVYU1gc01//rYkNqKR0smiR3PVnprV05Mpw9dk+gJ9oipt8rjvZuarwdTiS0U30MXUG5pSlPjwjIiM6NUD3g1BQiW6XF4qIIIs7vdDEXs3iXZLnZjsdLbs0uj5+lIKfGycy9yfjytP5gvmLATaZvs4+UE/ZfwFlhC1p202LwiDqMBaFbQ+9Bsl5Jrrt293DdNQIGm3CWoMaEBz jay.tischler@wholefoods.com


  tasks:
#    - name: Install standard packages
#      apt: pkg={{ item }} state=latest
#      with_items:
#        - nginx
#        - php5-fpm
#        - ncdu
#        - finger
#        - fail2ban
#        - lsb-release
#        - scrot

    - name: Set the hostname in /etc/hostname
      shell: echo {{ ansible_hostname }} > /etc/hostname
      when: ansible_hostname is defined

    - name: Set the hostname
      shell: hostname {{ ansible_hostname }}
      when: ansible_hostname is defined
