users_groups:
- name: devops
  gid: 1500
- name: api
  gid: 1501
- name: administrators
  gid: 1502
- name: sudo
  gid: 1503
- name: developers
  gid: 1505
#developers Group with whitelist of commands for sudo
# make sure developers get denied access on all bastion servers, netcat and sh, bash, ssh perhaps
# How to Remove a group
#- name: hr
#  state: absent
