---
- name: Load OS specific values
  include_vars: "{{ ansible_os_family }}.yml"
  with_first_found:
   - "{{ ansible_distribution }}.yml"
   - "{{ ansible_os_family }}.yml"
   - default.yml

- include: add_groups.yml

- include: users.yml

- include: remove_groups.yml

- include: ssh_keys.yml

- include: sudo.yml

#- include: groups.yaml
#- include: keys.yaml
#- include: users.yaml

#- include: ../../../includes/users.yaml
#- include: groups.yaml
#- include: ../../../includes/users.yaml
#- include: ../../../includes/keys.yaml
