---
- name: Copy add_agent.sh script
  copy: src=add_agent.sh dest=/tmp/add_agent.sh mode=755 owner=root group=root

- name: Add agent to the server
  shell: /tmp/add_agent.sh "{{item.hostname}}" "{{item.ip}}"
  with_items: client_ips
  notify:
  - restart ossec

- name: Get all client keys from OSSEC server to ansible server
  fetch: src=/var/ossec/etc/client.keys dest=/tmp/client.keys flat=yes

#handlers:
#  - name: restart ossec
#    service: name=ossec state=restarted
