---
- name: Install gcc postgres and mysql
  apt: pkg={{item}} state=installed
  #yum: name="{{item}}" state=present
  with_items:
    - gcc
    #- postgresql-devel
    - libpq-dev
    #- mysql-devel
    - libmysqld-dev
  
- name: Download Ossec server/agent 
  get_url: url="{{ossec_url}}" dest="{{ossec_path}}".tar.gz
 
- name: Extract Ossec server code
  unarchive: copy=no src="{{ossec_path}}".tar.gz dest="{{extract_path}}" creates="{{ossec_path}}"
 
- name: Copy the Ossec_input file
  template: src=ossec_client_input.j2 dest="{{ossec_path}}/ossec_client_input.txt"
 
- name: Install Ossec-agent
  shell: ./install.sh < ossec_client_input.txt 
  args:
    chdir: "{{ossec_path}}"
    creates: /var/ossec/etc/ossec.conf
 
- name: Get the client key from server
  copy: src=/tmp/client.keys dest=/var/ossec/etc/client2.keys  
 
- name: Extract only the key for current client
  shell: grep "{{ ansible_ssh_host }}" /var/ossec/etc/client2.keys > /var/ossec/etc/client.keys
  #shell: grep "{{ inventory_hostname }}" /var/ossec/etc/client2.keys > /var/ossec/etc/client.keys
 
- name: Delete other client keys   
  file: name=/var/ossec/etc/client2.keys state=absent
 
- name: Start Ossec server
  service: name=ossec state=started
