---
#
# file: api-ansible/common/tasks/main.yaml
#
- name: Updating Packages
  apt: update_cache=yes cache_valid_time=3600 upgrade=safe #only update if has not run in last hour
  tags: system

- name: Install list of packages
  apt: pkg={{item}} state=installed
  with_items:
  - git
  - finger
#  - fail2ban
  - unattended-upgrades

- name: Copy 50unattended-upgrades into /etc/apt/apt.conf.d
  action: copy src=50unattended-upgrades dest=/etc/apt/apt.conf.d/50unattended-upgrades force=yes

- name: Copy 20auto-upgrades into /etc/apt/apt.conf.d
  action: copy src=20auto-upgrades dest=/etc/apt/apt.conf.d/20auto-upgrades

#- name: Disallow password authentication
#  action: lineinfile dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present
#  notify: restart ssh
 
- name: Adjust APT update intervals
  action: copy src=apt_periodic dest=/etc/apt/apt.conf.d/10periodic

- name: Make sure unattended-upgrades only installs from $ubuntu_release-security
  action: lineinfile dest=/etc/apt/apt.conf.d/50unattended-upgrades regexp="trusty-updates" state=absent
 
- name: Setup ufw
  action: shell ufw allow 22/tcp
 
#- name: Setup ufw
#  action: shell ufw allow 443/tcp
 
- name: Enable ufw
  action: shell echo 'y' | ufw enable
 
- name: Disallow root SSH access
  action: lineinfile dest=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin no" state=present

- name: Update Sudo access for sudo group
  #action: lineinfile dest=/etc/sudoers regexp="^%sudo ALL=(ALL:ALL) ALL" line="%sudo ALL=(ALL) NOPASSWD:ALL" state=present
  action: lineinfile dest=/etc/sudoers regexp="^%s\sALL=\(ALL:ALL\)\s+ALL" line="%sudo ALL=(ALL) NOPASSWD:ALL" state=present
