---
#
# file: devops-ansible/common/tasks/main.yaml
#  auto-updates for yum and apt now take place in roles/auto-updates
#
- name: Updating Packages
  apt: update_cache=yes cache_valid_time=3600 upgrade=safe #only update if has not run in last hour
  tags: system
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Updating Packages
  yum: name={{item}} state=present
  with_items:
  - vim
  - git
  - finger
  - yum-updatesd
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Install list of packages
  apt: pkg={{item}} state=installed
  with_items:
  - git
  - finger
#  - fail2ban
  - unattended-upgrades
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

#- name: Disallow password authentication
#  action: lineinfile dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present
#  notify: restart ssh
 
 
#- name: Setup ufw
#  action: shell ufw allow 22/tcp
#  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
 
#- name: Setup ufw
#  action: shell ufw allow 443/tcp
 
#- name: Enable ufw
#  action: shell echo 'y' | ufw enable
#  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
 
- name: Disallow root SSH access
  action: lineinfile dest=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin no" state=present


# We do not need sudo for the nat servers as no users will be deployed here.

#- name: Update Sudo access for sudo group
#  action: lineinfile dest=/etc/sudoers regexp="^%sudo ALL=(ALL:ALL) ALL" line="%sudo ALL=(ALL) NOPASSWD:ALL" state=present
#  action: lineinfile dest=/etc/sudoers regexp="^%s\sALL=\(ALL:ALL\)\s+ALL" line="%sudo ALL=(ALL) NOPASSWD:ALL" state=present
